package input

import "time"

type UserInput struct {
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

//Generated by Micagen at 2021-10-27 08:47:24.9857741 +0700 +07 m=+0.024659301
