package input

type InputIDUser struct { 
ID int `uri:"id" binding:"required"` 
}

type UserInput struct { 
Username string `json:"username"` 
Password string `json:"password"` 
}

//Generated by Micagen at 27 Oktober 2021