package input

import "time"

type InputIDUser struct {
	ID int `uri:"id" binding:"required"`
}

type UserInput struct {
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

//Generated by Micagen at 27 Oktober 2021
