package service

import (
	"github.com/ekokurniadi/micagen/entity"
	"github.com/ekokurniadi/micagen/input"
	"github.com/ekokurniadi/micagen/repository"
)

type UserService interface {
	UserServiceGetAll() ([]entity.User, error)
	UserServiceGetByID(inputID input.InputIDUser) (entity.User, error)
	UserServiceCreate(input input.UserInput) (entity.User, error)
	UserServiceUpdate(inputID input.InputIDUser, inputData input.UserInput) (entity.User, error)
	UserServiceDeleteByID(inputID input.InputIDUser) (bool, error)
}
type userService struct {
	repository repository.UserRepository
}

func NewUserService(repository repository.UserRepository) *userService {
	return &userService{repository}
}
func (s *userService) UserServiceCreate(input input.UserInput) (entity.User, error) {
	user := entity.User{}
	user.Username = input.Username
	user.Password = input.Password
	newUser, err := s.repository.SaveUser(user)
	if err != nil {
		return newUser, err
	}
	return newUser, nil
}
func (s *userService) UserServiceUpdate(inputID input.InputIDUser, inputData input.UserInput) (entity.User, error) {
	user, err := s.repository.FindByIDUser(inputID.ID)
	if err != nil {
		return user, err
	}
	user.Username = inputData.Username
	user.Password = inputData.Password

	updatedUser, err := s.repository.UpdateUser(user)

	if err != nil {
		return updatedUser, err
	}
	return updatedUser, nil
}
func (s *userService) UserServiceGetByID(inputID input.InputIDUser) (entity.User, error) {
	user, err := s.repository.FindByIDUser(inputID.ID)
	if err != nil {
		return user, err
	}
	return user, nil
}
func (s *userService) UserServiceGetAll() ([]entity.User, error) {
	users, err := s.repository.FindAllUser()
	if err != nil {
		return users, err
	}
	return users, nil
}
func (s *userService) UserServiceDeleteByID(inputID input.InputIDUser) (bool, error) {
	_, err := s.repository.FindByIDUser(inputID.ID)
	if err != nil {
		return false, err
	}
	_, err = s.repository.DeleteByIDUser(inputID.ID)
	if err != nil {
		return false, err
	}
	return true, nil
}

//Generated by Micagen at 27 Oktober 2021
