package repository

import (
	"github.com/ekokurniadi/micagen/entity"
	"gorm.io/gorm"
)

type UserRepository interface {
	SaveUser(user entity.User) (string, error)
	UpdateUser(user entity.User) (string, error)
	FindByIDUser(ID int) (entity.User, error)
	FindAllUser() ([]entity.User, error)
	DeleteByIDUser(ID int) (string error)
}

type userRepository struct {
	db *gorm.DB
}

func NewUserRepository(db *gorm.DB) *userRepository {
	return &userRepository{db}
}

func (r *userRepository) SaveUser(user entity.User) (entity.User, error) {
	err := r.db.Create(&user).Error
	if err != nil {
		return user, err
	}
	return user, nil

}
func (r *userRepository) FindByIDUser(ID int) (entity.User, error) {
	var user entity.User
	err := r.db.Where("id = ? ", ID).Find(&user).Error
	if err != nil {
		return user, err
	}
	return user, nil

}

//Generated by Micagen at 2021-10-27 08:47:24.9927559 +0700 +07 m=+0.031641101
