package formatter

import "github.com/ekokurniadi/micagen/entity"

type UserFormatter struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}

func FormatUser(user entity.User) UserFormatter {
	userFormatter := UserFormatter{}
	userFormatter.ID = user.ID
	userFormatter.Username = user.Username
	userFormatter.Password = user.Password
	return userFormatter
}
func FormatUsers(users []entity.User) []UserFormatter {
	usersFormatter := []UserFormatter{}
	for _, user := range users {
		userFormatter := FormatUser(user)
		usersFormatter = append(usersFormatter, userFormatter)
	}
	return usersFormatter
}

//Generated by Micagen at 27 Oktober 2021
